"""
RedStoneX 引擎核心
"""
from __future__ import annotations
import typing
__all__: list[str] = ['COMPARISON', 'CoreBlock', 'CoreComparatorMode', 'CoreComparatorSource', 'CoreConnectiveObject', 'CoreCustomObject', 'CoreLineObject', 'CorePowerType', 'CoreRelaySource', 'CoreSimulator', 'CoreSlotObject', 'CoreSourceObject', 'CoreTorchSource', 'NONE', 'STRONG', 'SUBTRACTION', 'WEAK', 'register_plugin_from_ptr']
class CoreBlock(CoreLineObject):
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class CoreComparatorMode:
    """
    Members:
    
      COMPARISON
    
      SUBTRACTION
    """
    COMPARISON: typing.ClassVar[CoreComparatorMode]  # value = <CoreComparatorMode.COMPARISON: 0>
    SUBTRACTION: typing.ClassVar[CoreComparatorMode]  # value = <CoreComparatorMode.SUBTRACTION: 1>
    __members__: typing.ClassVar[dict[str, CoreComparatorMode]]  # value = {'COMPARISON': <CoreComparatorMode.COMPARISON: 0>, 'SUBTRACTION': <CoreComparatorMode.SUBTRACTION: 1>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class CoreComparatorSource(CoreSourceObject):
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def delay(self) -> int:
        ...
    @property
    def mode(self) -> CoreComparatorMode:
        ...
class CoreConnectiveObject:
    def connect(self, arg0: CoreConnectiveObject) -> None:
        ...
    def disconnect(self, arg0: CoreConnectiveObject) -> None:
        ...
    @property
    def id(self) -> int:
        ...
    @property
    def is_lossless(self) -> bool:
        ...
    @property
    def is_weak_transmissible(self) -> bool:
        ...
    @property
    def power(self) -> int:
        ...
    @property
    def uri(self) -> str:
        ...
class CoreCustomObject(CoreConnectiveObject):
    def __getattr__(self, arg0: str) -> typing.Any:
        ...
    def __init__(self, arg0: str, **kwargs) -> None:
        ...
class CoreLineObject(CoreConnectiveObject):
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class CorePowerType:
    """
    Members:
    
      NONE
    
      WEAK
    
      STRONG
    """
    NONE: typing.ClassVar[CorePowerType]  # value = <CorePowerType.NONE: 0>
    STRONG: typing.ClassVar[CorePowerType]  # value = <CorePowerType.STRONG: 2>
    WEAK: typing.ClassVar[CorePowerType]  # value = <CorePowerType.WEAK: 1>
    __members__: typing.ClassVar[dict[str, CorePowerType]]  # value = {'NONE': <CorePowerType.NONE: 0>, 'WEAK': <CorePowerType.WEAK: 1>, 'STRONG': <CorePowerType.STRONG: 2>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class CoreRelaySource(CoreSourceObject):
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def delay(self) -> int:
        ...
    @property
    def relay_power(self) -> int:
        ...
class CoreSimulator:
    def __init__(self) -> None:
        ...
    def add_tick_breakpoint(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def bind_object(self, arg0: CoreConnectiveObject) -> None:
        ...
    def pause(self) -> None:
        ...
    def remove_tick_breakpoint(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def resume(self) -> None:
        ...
    def run(self) -> None:
        ...
    def step(self) -> None:
        ...
class CoreSlotObject(CoreConnectiveObject):
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: CoreConnectiveObject, arg2: CorePowerType) -> None:
        ...
class CoreSourceObject(CoreConnectiveObject):
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def max_delay(self) -> int:
        ...
class CoreTorchSource(CoreSourceObject):
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def delay(self) -> int:
        ...
    @property
    def torch_power(self) -> int:
        ...
def register_plugin_from_ptr(arg0: str, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: typing.SupportsInt | typing.SupportsIndex, arg3: typing.SupportsInt | typing.SupportsIndex) -> None:
    ...
COMPARISON: CoreComparatorMode  # value = <CoreComparatorMode.COMPARISON: 0>
NONE: CorePowerType  # value = <CorePowerType.NONE: 0>
STRONG: CorePowerType  # value = <CorePowerType.STRONG: 2>
SUBTRACTION: CoreComparatorMode  # value = <CoreComparatorMode.SUBTRACTION: 1>
WEAK: CorePowerType  # value = <CorePowerType.WEAK: 1>
