"""
RedStoneX 引擎核心
"""
from __future__ import annotations
import typing
__all__: list[str] = ['COMPARISON', 'CoreBlock', 'CoreComparatorSource', 'CoreComparatorSourceMode', 'CoreConnectiveObject', 'CoreCustomObject', 'CoreLineObject', 'CoreLogLevel', 'CorePowerType', 'CoreRelaySource', 'CoreSimulator', 'CoreSlotObject', 'CoreSourceObject', 'CoreTorchSource', 'DEBUG', 'ERROR', 'INFO', 'NONE', 'STRONG', 'SUBTRACTION', 'WARN', 'WEAK', 'register_plugin_from_ptr']
class CoreBlock(CoreLineObject):
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class CoreComparatorSource(CoreSourceObject):
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def set_mode(self, arg0: CoreComparatorSourceMode) -> None:
        ...
    @property
    def _calculate_slot_a_ptr(self) -> int:
        ...
    @property
    def _calculate_slot_b_ptr(self) -> int:
        ...
    @property
    def _input_slot_ptr(self) -> int:
        ...
    @property
    def _output_slot_ptr(self) -> int:
        ...
    @property
    def delay(self) -> int:
        ...
    @property
    def mode(self) -> CoreComparatorSourceMode:
        ...
class CoreComparatorSourceMode:
    """
    Members:
    
      COMPARISON
    
      SUBTRACTION
    """
    COMPARISON: typing.ClassVar[CoreComparatorSourceMode]  # value = <CoreComparatorSourceMode.COMPARISON: 0>
    SUBTRACTION: typing.ClassVar[CoreComparatorSourceMode]  # value = <CoreComparatorSourceMode.SUBTRACTION: 1>
    __members__: typing.ClassVar[dict[str, CoreComparatorSourceMode]]  # value = {'COMPARISON': <CoreComparatorSourceMode.COMPARISON: 0>, 'SUBTRACTION': <CoreComparatorSourceMode.SUBTRACTION: 1>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class CoreConnectiveObject:
    @staticmethod
    def create_view(arg0: typing.SupportsInt | typing.SupportsIndex) -> CoreConnectiveObject:
        ...
    def connect(self, arg0: CoreConnectiveObject) -> bool:
        ...
    def disconnect(self, arg0: CoreConnectiveObject) -> bool:
        ...
    @property
    def connect_count(self) -> int:
        ...
    @property
    def id(self) -> int:
        ...
    @property
    def is_lossless(self) -> bool:
        ...
    @property
    def is_weak_transmissible(self) -> bool:
        ...
    @property
    def limit(self) -> int:
        ...
    @property
    def power(self) -> int:
        ...
    @property
    def uri(self) -> str:
        ...
class CoreCustomObject(CoreConnectiveObject):
    def __getattr__(self, arg0: str) -> typing.Any:
        ...
    def __init__(self, arg0: str, **kwargs) -> None:
        ...
class CoreLineObject(CoreConnectiveObject):
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class CoreLogLevel:
    """
    Members:
    
      DEBUG
    
      INFO
    
      WARN
    
      ERROR
    """
    DEBUG: typing.ClassVar[CoreLogLevel]  # value = <CoreLogLevel.DEBUG: 0>
    ERROR: typing.ClassVar[CoreLogLevel]  # value = <CoreLogLevel.ERROR: 3>
    INFO: typing.ClassVar[CoreLogLevel]  # value = <CoreLogLevel.INFO: 1>
    WARN: typing.ClassVar[CoreLogLevel]  # value = <CoreLogLevel.WARN: 2>
    __members__: typing.ClassVar[dict[str, CoreLogLevel]]  # value = {'DEBUG': <CoreLogLevel.DEBUG: 0>, 'INFO': <CoreLogLevel.INFO: 1>, 'WARN': <CoreLogLevel.WARN: 2>, 'ERROR': <CoreLogLevel.ERROR: 3>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class CorePowerType:
    """
    Members:
    
      NONE
    
      WEAK
    
      STRONG
    """
    NONE: typing.ClassVar[CorePowerType]  # value = <CorePowerType.NONE: 0>
    STRONG: typing.ClassVar[CorePowerType]  # value = <CorePowerType.STRONG: 2>
    WEAK: typing.ClassVar[CorePowerType]  # value = <CorePowerType.WEAK: 1>
    __members__: typing.ClassVar[dict[str, CorePowerType]]  # value = {'NONE': <CorePowerType.NONE: 0>, 'WEAK': <CorePowerType.WEAK: 1>, 'STRONG': <CorePowerType.STRONG: 2>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class CoreRelaySource(CoreSourceObject):
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def set_delay(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def _input_slot_ptr(self) -> int:
        ...
    @property
    def _output_slot_ptr(self) -> int:
        ...
    @property
    def delay(self) -> int:
        ...
    @property
    def relay_power(self) -> int:
        ...
class CoreSimulator:
    def __init__(self) -> None:
        ...
    def add_tick_breakpoint(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def bind_object(self, arg0: CoreConnectiveObject) -> None:
        ...
    def enable_logging(self, arg0: CoreLogLevel) -> None:
        ...
    def pause(self) -> None:
        ...
    def remove_tick_breakpoint(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def resume(self) -> None:
        ...
    def run(self) -> None:
        ...
    def step(self) -> bool:
        ...
class CoreSlotObject(CoreConnectiveObject):
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: CoreConnectiveObject, arg2: CorePowerType) -> None:
        ...
class CoreSourceObject(CoreConnectiveObject):
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def max_delay(self) -> int:
        ...
class CoreTorchSource(CoreSourceObject):
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def _bottom_slot_ptr(self) -> int:
        ...
    @property
    def _power_slot_ptr(self) -> int:
        ...
    @property
    def delay(self) -> int:
        ...
    @property
    def torch_power(self) -> int:
        ...
def register_plugin_from_ptr(arg0: str, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: typing.SupportsInt | typing.SupportsIndex, arg3: typing.SupportsInt | typing.SupportsIndex) -> None:
    ...
COMPARISON: CoreComparatorSourceMode  # value = <CoreComparatorSourceMode.COMPARISON: 0>
DEBUG: CoreLogLevel  # value = <CoreLogLevel.DEBUG: 0>
ERROR: CoreLogLevel  # value = <CoreLogLevel.ERROR: 3>
INFO: CoreLogLevel  # value = <CoreLogLevel.INFO: 1>
NONE: CorePowerType  # value = <CorePowerType.NONE: 0>
STRONG: CorePowerType  # value = <CorePowerType.STRONG: 2>
SUBTRACTION: CoreComparatorSourceMode  # value = <CoreComparatorSourceMode.SUBTRACTION: 1>
WARN: CoreLogLevel  # value = <CoreLogLevel.WARN: 2>
WEAK: CorePowerType  # value = <CorePowerType.WEAK: 1>
